# Generated by Django 3.0.4 on 2020-04-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_play'),
        ('main', '0002_auto_20200317_1047'),
    ]

    operations = [
    ]
