# Generated by Django 3.0.5 on 2020-04-25 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200421_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('12cc4674-cc11-4a22-a736-76a7e575492e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
